### ISSUE TITLE
Using symbolic links instead of cp in 02-variant_calling.md

### ISSUE THREAD

**Issue by taylorreiter** [datacarpentry/wrangling-genomics#110]
In [datacarpentry/wrangling-genomics/_episodes/02-variant_calling.md](https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/_episodes/02-variant_calling.md), under the "Setting up" section, the reference genome and fastq files are copied from one directory to another. This wastes space on the hard drive, and though it is not a problem for this lesson as far as size goes, in general, I think it is better practice to teach symbolic links. Thoughts?

**Comment by standage** [comment]
+1

The materials don't cover symlinks up to this point, but the concept of a "file shortcut" isn't too complex. I'd suggest that it would be best to squeeze an intro to symlinks into the file/directory handling module, but even if there's no time to cover it prior to the variant calling module, it shouldn't require too much of a diversion to introduce symlinks at that point.

**Comment by taylorreiter** [comment]
Rewrote for UC Davis Genomics workshop here:
https://github.com/taylorreiter/wrangling-genomics/blob/gh-pages/_episodes/02-variant_calling.md

**Comment by fpsom** [comment]
Thank you @taylorreiter @standage for the comments - I do agree it makes sense to address this as it is a rather useful concept / command. I would also agree to be put here as a short intro, rather than in the [shell-genomics lesson](http://www.datacarpentry.org/shell-genomics/) as it feels more connected here.

Also, looking at the updated version @taylorreiter provided, the explanation could be a bit more enhanced (e.g. explaining the difference between link and symbolic link).

@taylorreiter: do you think it would be possible to put a PR here addressing this?

**Comment by taylorreiter** [comment]
@fpsom yes! I will have a PR in within the next two days, including an enhanced explanation of link vs. symbolic link.

**Comment by fpsom** [comment]
Issue addressed with [PR #155](https://github.com/datacarpentry/wrangling-genomics/pull/115).
