### ISSUE TITLE
moving hidden files is confusing

### ISSUE THREAD

**Issue by taylorreiter** [datacarpentry/wrangling-genomics#112]
Under the header "Running FastQC" in [wrangling-genomics/_episodes/00-quality-control.md](https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/_episodes/00-quality-control.md), the command:
```
 mv ~/.dc_sampledata_lite/untrimmed_fastq/ ~/dc_workshop/data/
```
Is confusing. It's not clear why hidden files existed in the first place, and if this step is missed, the paths in the rest of the lessons no longer work. 

Pointed out by @ljcohen while she was teaching the lesson.

**Comment by ljcohen** [comment]
Since some learners are very new to moving files around, it takes time away from the lesson to move files around. I was tempted to keep working in the `~/.dc_sampledata_lite/untrimmed_fastq/` directory where the files were originally placed on the aws instance. It was unclear why we should move the files to a new directory. Then we realized that the paths for the subsequent lessons required the files be in the new location.

A few thoughts:

1. Why store files in the hidden location `~/.dc_sampledata_lite/`? Is this to teach keeping raw data in a backup location, just in case? We already went over this with the subset of data `~/dc_sample_data/untrimmed_fastq/backup/` in the [Working with Files and Directories](http://www.datacarpentry.org/shell-genomics/03-working-with-files/) lesson. The difference between the full dataset `~/.dc_sample_data_lite/` and the subset `~/dc_sample_data/` could be more clearly differentiated in the lesson notes.
2. Would it be possible to change the location on the aws image from `~/.dc_sampledata_lite/` to be in the final location, '~/dc_workshop/data/` to eliminate confusion, and students having to move the files?

**Comment by standage** [comment]
I actually think it's wise to keep a hidden copy of all of the data somewhere. It's very helpful in case at any time one of the students badly botches a command. Instead of "oh crap let's try to download the data again" we can be like "ok let's just copy from the backup and start again."

Perhaps we should have a bash function/alias/command in the `~/.bashrc` file that copies or symlinks the data to a common working directory? We can even hide this from the students, and just make sure the instructors and helpers know that if at any time a working directory is borked beyond repair, you can just nuke it and re-run this setup command.

Thoughts?

**Comment by standage** [comment]
To the extent that we want to teach students how to copy files and make symlinks, we can still do that, but in a way that is more relevant to how they'll work on a routine basis in genomics research.

**Comment by ljcohen** [comment]
Agree it's a good idea to keep a hidden copy and not tell students. The way it is written in the QC lesson now, it states ([halfway down the page](https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/_episodes/00-quality-control.md)):
"
Running FastQC
We will be working with a set of sample data that is located in a hidden directory (.dc_sampledata_lite)
"
Then the command is to move the files, not copy them:

```
$ mv ~/.dc_sampledata_lite/untrimmed_fastq/ ~/dc_workshop/data/
```
I like your idea of creating a bash function to automatically copy the files from the backup location `~/.dc_sampledata_lite/untrimmed_fastq/` so it doesn't interrupt the lesson by having to explain to the students: a) we have these files in a hidden directory (why? not sure) b) we are moving these files so we can work with them.

**Comment by standage** [comment]
I also like suggestion from @bluegenes to make the original data files write-protected (for additional safety). I haven't checked but I don't think they are.

**Comment by bluegenes** [comment]
If the reason for the `mv` instead of `cp` is the size of the data set, we could keep the data in the hidden, write-protected directory, and use symbolic links (which we're teaching anyway) to link the data into `~/dc_workshop_data`. This also avoids any issues / file checking people will need to do if a connection issue/hangup occurs during a data `mv`.

**Comment by taylorreiter** [comment]
addressed by #133! We download the fastq files instead. However, they are still hidden in a `.backup` directory, and can be moved if downloading is too slow. @fpsom, can we close this?

**Comment by fpsom** [comment]
Yes, I think we can safely close this. Thanks @taylorreiter !

I'll leave it open until the end of the week (just in case there are any objections), and close it then.

**Comment by fpsom** [comment]
No further comments, so I'm closing the issue! Thanks all for your comments and feedback!
