### ISSUE TITLE
Trimmomatic options are confusing

### ISSUE THREAD

**Issue by ekirving** [datacarpentry/wrangling-genomics#131]
The introduction to Trimmomatic and the example options are a little confusing.

Specifically, this section introduces the "phred33" and "phred64" terminology, which have not been used before and the differences are not explained. The previous section simply says "... our data uses the standard Sanger quality PHRED score encoding, using by Illumina version 1.8 onwards" but does not reference phred33 as the encoding type. It's a little odd that in this section the example uses phred64 as this format is rather uncommon now.

This section also introduces the concept of Illumina adapters, but does not explain what adaptors are or why they need to be removed from the FASTQ files.

**Comment by fpsom** [comment]
Thanks @ekirving for this comment! There is a mention of phred scores in the Quality episode, where the is a chart showing how the symbol, the quality and the actual error connect to each other. However, you are absolutely correct that a more coherent description on the Trimmomatic introduction is need.

Right now, we are planning a major restructuring of the lesson so that we bring it up to date (including newer versions of the involved tools and the overall installation process). So I'll put the `wait` label so that it's addressed when the new content is in.

**Comment by ErinBecker** [comment]
@fpsom - was this comment addressed in the new version?

**Comment by fpsom** [comment]
Yes, it has been addressed in the updated 2nd episode [02-quality-control](https://datacarpentry.org/wrangling-genomics/02-quality-control/index.html)

**Comment by ErinBecker** [comment]
Thanks for clarifying @fpsom.
