### ISSUE TITLE
add explicit commands to copy fastq files from .backup into dc_workshop/data

### ISSUE THREAD

**Issue by taylorreiter** [datacarpentry/wrangling-genomics#140]
We need to add explicit instructions to the episode 02 Assessing Read Quality to copy the `fastq` files from `.backup/untrimmed_fastq/*fastq.gz`. 

The download worked quickly for some learners, but was very slow for others. An alternative would be to use a different instance type, as t2.medium has slow/moderate network speeds that are less reliable than other instances. However, this may cost most. A t2.medium costs $0.0464 per Hour and Low to Moderate network performance. A t3.medium costs $0.0416 per Hour and has up to 5 Gbps. An m5a.large costs $0.086 per Hour and has up to 10 Gbps.

**Comment by taylorreiter** [comment]
@ErinBecker 

potential improvement for the AWS image, upgrade from t2.medium to t3.medium

**Comment by ErinBecker** [comment]
@taylorreiter - I'm looking into changing our AMI setup to be able to use the t3 instance type instead of t2, but think we should also include the command for copying data from `.backup/`, as even with the faster instance type, some learners will still experience problems with the large data download. I'm working on a PR to add this command now.

**Comment by taylorreiter** [comment]
@ErinBecker I totally agree! Thank you for working on upgrading to t3 and for working toward adding a copying command!
