### ISSUE TITLE
setup page points to software pages but not to installation or download pages

### ISSUE THREAD

**Issue by mkuzak** [datacarpentry/wrangling-genomics#30]
It can be a very frustrating experience to work through the software pages in order to find how to download and install software. More so for novices who don't know what they're looking for. I think it would be useful to point to this place in the setup. This is what I would expect from the setup page.

**Comment by crazyhottommy** [comment]
agree. I sometimes spend a whole morning or afternoon just installing tools...

**Comment by JasonJWilliamsNY** [comment]
There is a workshop setup page for genomics as example here: https://jasonjwilliamsny.github.io/2017-08-28-nmsu/install.html I have no idea where this, because lots of pieces are scattered about. Learners should not have to set up/install anything on cloud. However, There was (no idea where it is now) a separate repo for self-guided learners that addressed doing it on their own cloud instance, or which could address doing it on a local machine. Keep in mind, that workshop was originally meant to 'force' learners to do things on cloud/hpc as part of their learning objective, so this is a deeper issue to address.

**Comment by mkuzak** [comment]
@JasonJWilliamsNY I agree. I think what is confusing is that in the setup I would expect a list of things I need to setup on my machine. Maybe better to say everything is installed in the vm so you don't need to install anything (although you still need to install some software to connect to the cloud, maybe this should go into setup) and refer to the separate document describing what's on the vm.

**Comment by JasonJWilliamsNY** [comment]
@mkuzak Agree. A DC Genomics setup repo could be a place to manage all of those items, including perhaps as @fpsom suggests some makefiles.

**Comment by ErinBecker** [comment]
See also: https://github.com/datacarpentry/wrangling-genomics/issues/32

**Comment by ErinBecker** [comment]
@fpsom - This one is a little out of my element. Would you be able to take a try at putting in a PR to resolve this and #32?

**Comment by ErinBecker** [comment]
Creating meta-issue in genomics-workshop. See link above.
