### ISSUE TITLE
Importing refference genome and checksum

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [datacarpentry/wrangling-genomics#35]
In Cloud lesson, there is a section on importing using wget. I think this belongs here, and could be the place to import the ecoli reference. This would also be a QC step to introduce the idea of checksums.

**Comment by ErinBecker** [comment]
Thanks for catching this @JasonJWilliamsNY. 

@fpsom - I've assigned you to this since we're both working on the lessons today and I don't remember much about checksums. I used it when I was in graduate school, but wouldn't be the most obvious choice to write an explanation. I'm happy to try, however, if your plate is full for the day.
