### ISSUE TITLE
Access to files for self-learners (and maintainers)

### ISSUE THREAD

**Issue by lexnederbragt** [datacarpentry/wrangling-genomics#75]
How would self-learners interested in going over this material be able to run the analyses? Can we give them access to the input files? An Amazon image?

Similarly, if I want to address some remaining issues, I would need to do many of the steps normally run at a workshop, or at least get my hands on the output files...

**Comment by fpsom** [comment]
I agree with @lexnederbragt on that. As far as I can see, the following do exist:
1. The instructions on how to connect to AWS [here](http://www.datacarpentry.org/cloud-genomics/discuss/)
2. The name of the image that can be used to create the instance, i.e. **ami-07b4456a**
3. Some output files (specifically the trimmed `fastq` files) and the corresponding reference genome are available in the wrangling genomics repo [here](https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/variant_calling.tar.gz)

**Comment by tracykteal** [comment]
As @fpsom says, people can spin up their own AMI, but we don't have a way for them to spin it up on our account. They would need to have their own AWS account, which is a barrier for using this for self-learning. 

One of the things to consider after this release, and something on the docket for the Advisory meeting, is if we should have the whole thing in something like a Docker container, so people can use or deploy it however. That does mean people would still need to install and use Docker, but that's getting more straightforward.

**Comment by fpsom** [comment]
I am absolutely for the idea of using Docker as the means of showcasing tools (in the sense of having one docker image per tool used). I see two arguments that can be made against:

1. Docker, although useful, will not be "tolerated" in an HPC environment. On the flip-side, singularity can directly use docker images, and is compatible with the standard security measures.
2. We need to spend time and effort to create slim, tool-specific docker images, as most of the existing ones are usually in the form of bundles.

Just some thoughts on this.

**Comment by tracykteal** [comment]
Thanks for those thoughts @fpsom. I agree this is a big issue with a lot to think about. So, it's important to have this discussion. It's particularly challenging because the space is changing, so we want to be current and make use of tools that are effective and useful for us and learners, but not bleeding edge current. 

Docker is something that many (most?) HPCs are now supporting, so it something that could actually make it easier to deploy on a HPC. 

I think @lexnederbragt started this issue asking about current availability of files. I see there's already an issue on docker deployment https://github.com/datacarpentry/genomics-workshop/issues/28, so I linked them, and we can continue the discussion there.

**Comment by ErinBecker** [comment]
Creating meta-issue in genomics-workshop. See link above.

**Comment by DCGenomics** [comment]
A bit of an aside, but I really like this explanation for using docker.  Its really simple and easy:  https://github.com/BioDepot/BioDepot-workflow-builder (just referring to the gh readme, not an endorsement of the rest of the product)

Apparently it was developed with a lot of testing on undergrads

**Comment by DCGenomics** [comment]
Singularity will also help with the HPC situation a bit (particularly in an NIH context)
