### ISSUE TITLE
Discuss how FASTQC is done for multiple files

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/wrangling-genomics#8]
In a recent workshop, we got a few questions on how FASTQC can be done on multiple files, and how could you view the results of multiple files.

We can emphasize that here we're teaching how to do this for one file, and that later we'll talk about how to do it for multiple files.

For viewing, we should emphasize that you wouldn't visualize the output for all your FASTQC files, but that you would look at representative files, or discuss how you would use the output of FASTQC for multiple files.

**Comment by hoytpr** [comment]
Now that we're doing sequencing in the Core, this is a legit question. We could talk about bash scripting to submit a series of jobs, but my philosophy is to defend my ignorant biologist friends, and that would be pretty advanced for them. However, I wouldn't suggest that the SOP is to look at a few files because the quality between samples (libraries) multiplexed in a single Illumina run can vary tremendously. 
With our NextSeq500 data, the fastq files are output as four separate files simply based on which camera was used. In this case a bit of not-too-difficult information might be to suggest using 'cat' to append and merge the files together prior to fastqc.

**Comment by crazyhottommy** [comment]
actually, I am using [multiQC](http://multiqc.info/) to collate all fastqc report into a single html and that helped me a lot! not sure it is OK to introduce in the lesson.

**Comment by JasonJWilliamsNY** [comment]
@tracykteal I commented somewhere that since all fastqc results generate a summary.txt, we should `cat` them all into a single file (already done in the lesson) and use your new shell/grep skills to pick out the FAILS. 
As for @crazyhottommy comment - I think think maintainers can introduce new tools, but have to think about our goal, which is not so much to teach tools but practices. If multiQC is something we must use, that's fine. However, sometimes doing things the "longer" way will introduce problems the learners have to solve (such as arranging and organizing their outputs). Just my opinion.

**Comment by crazyhottommy** [comment]
I agree that `cat` all summary files together should serve good enough. people can then even load that into R making visualizations (by themselves).

**Comment by ErinBecker** [comment]
It sounds like the consensus here is to have learners `cat` their summary files together and `grep` out the fails. 

@crazyhottommy would you or one of the other maintainers be able to put in a PR for this? 
@fpsom @lexnederbragt @jrherr

**Comment by ErinBecker** [comment]
Closed with #46.
