### ISSUE TITLE
Issues with software installations on Mac

### ISSUE THREAD

**Issue by gtehennepe** [datacarpentry/wrangling-genomics#88]
I started with Setup and followed along with the instructions on a Mac instead of an Amazon instance, since all of the packages indicated they are available for Mac. I used the source download approach as I didn't have homebrew or conda installed. This went fine except for BCFtools, which failed to compile. I didn't chase the problem, but I'm guessing a missing library:

```
cd htslib-1.5 && /Library/Developer/CommandLineTools/usr/bin/make lib-static
gcc -g -Wall -O2 -I.  -c -o cram/cram_io.o cram/cram_io.c
cram/cram_io.c:60:10: fatal error: 'lzma.h' file not found
#include <lzma.h>
         ^~~~~~~~
1 error generated.
make[1]: *** [cram/cram_io.o] Error 1
make: *** [htslib-1.5/libhts.a] Error 2
```

I then tried installing homebrew and miniconda to see if they could successfully install BCFtools. Homebrew failed to install based on the command provided at https://brew.sh/. The miniconda install was successful, but then was unable to install BCFtools because it couldn't find BCFtools in the channels it searched:

```
PackageNotFoundError: Packages missing in current channels:
            
  - bcftools

We have searched for the packages in the following channels:
            
  - https://repo.continuum.io/pkgs/main/osx-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/osx-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/osx-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/osx-64
  - https://repo.continuum.io/pkgs/pro/noarch
```

Considering that Carpentry lessons are expected to run on all three platforms, it seems like the instructions need updating and testing on Mac and PC as well.

I should note I'm running on Mac OS 10.12.6.

**Comment by ErinBecker** [comment]
Thanks for putting in this issue @gtehennepe. @tracykteal and I spent some time last week going through the install instructions and decided that, since we're recommending learners to use the AMI (where all the software will already be installed), we won't be keeping the self-install instructions current for all operating systems. We've added language to the current setup page to clarify that the instructions are provided for the learner's reference and that we link to the software pages for more detailed installation instructions. We also added language to clarify that use of the AMI is prefered. 

Related PRs:

https://github.com/datacarpentry/genomics-workshop/pull/35
https://github.com/datacarpentry/genomics-workshop/pull/33
https://github.com/datacarpentry/genomics-workshop/pull/32
